#!/bin/bash
#
# @author Zeus Intuivo <zeus@intuivo.com>
#

red=`tput setaf 1`
cyan=`tput setaf 6`
blue23=`tput setaf 23`
blue33=`tput setaf 33`
blue30=`tput setaf 33`
gray238=`tput setaf 238`
yellow220=`tput setaf 220`
green=`tput setaf 2`
reset=`tput sgr0`

# docker rmi $(docker images -q -f "dangling=true")
echo "${blue23} docker rmi \$(docker images -q -f \"dangling=true\") ${reset}"

DANGLING_IMAGES=$(docker images -q -f "dangling=true")

if [ ! -z "${DANGLING_IMAGES}" ] ; then
  {
    echo "${blue30} • ${blue23} docker rmi ${DANGLING_IMAGES} ${reset}"
    docker rmi "${DANGLING_IMAGES}"
    wait
    docker rmi $(docker images -q -f "dangling=true")
  }
else
  {
    echo "${blue30} - empty - ${reset}"
    echo "${blue30} • ${blue23} No dangling images ${reset}"
  }
fi
