#!/bin/bash
#
# @author Zeus Intuivo <zeus@intuivo.com>
#

red=`tput setaf 1`
cyan=`tput setaf 6`
blue23=`tput setaf 23`
blue33=`tput setaf 33`
blue30=`tput setaf 33`
gray238=`tput setaf 238`
yellow220=`tput setaf 220`
green=`tput setaf 2`
reset=`tput sgr0`

# docker rm $(docker ps -q -f 'status=exited')
echo "${blue23} docker rm \$(docker ps -q -f  \"status=exited\") ${reset}"

EXITED_IMAGES=$(docker ps -q -f 'status=exited')

if [ ! -z "${EXITED_IMAGES}" ] ; then
  {
    echo "${blue30} • ${blue23} docker rmi ${EXITED_IMAGES} ${reset}"
    docker rm "${EXITED_IMAGES}"
    wait 
    docker rm $(docker ps -q -f 'status=exited')
  }
else
  {
    echo "${blue30} - empty - ${reset}"
    echo "${blue30} • ${blue23} No exited images found ${reset}"
  }
fi

