#!/bin/bash
#
# @author Zeus Intuivo <zeus@intuivo.com>
#

red=`tput setaf 1`
cyan=`tput setaf 6`
blue23=`tput setaf 23`
blue33=`tput setaf 33`
blue30=`tput setaf 33`
gray238=`tput setaf 238`
yellow220=`tput setaf 220`
green=`tput setaf 2`
reset=`tput sgr0`

echo "${blue23} docker rm \$(docker volume ls ) ${reset}"

DANGLING_VOLUMES=$(docker volume ls )

if [ -n "${DANGLING_VOLUMES}" ] ; then
  {
    echo "${blue30} • ${blue23} docker rm ${DANGLING_VOLUMES} ${reset}"
    docker rm "${DANGLING_VOLUMES}"
    wait
    # shellcheck disable=SC2046
    docker rm $(docker volume ls )
    wait
    docker volume prune
  }
else
  {
    echo "${blue30} - empty - ${reset}"
    echo "${blue30} • ${blue23} No volumes ${reset}"
  }
fi